eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
spring:
  application:
    name: order
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password: 123456
      url: jdbc:mysql://127.0.0.1/springcloud_shell?characterEncodingutf-8&useSSL=false
  jpa:
    show-sql: true
env:
  test5
person:
  name: lucy
  sex: male
